name: CI with Dependency Caching

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Add this step to prepare the Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # --- 1. Cache Step ---
      - name: prime-cache-c46fbd2
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          # Path to the pip cache directory
          path: ~/.cache/pip  
          # Key based on the required name and hashing requirements.txt
          key: cache-c46fbd2-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            cache-c46fbd2-

      # --- 2. Prime/Dependency Installation Step ---
      # This step only runs if the cache misses (first run or requirements.txt changed)
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      
      # --- 3. Cache Hit/Miss Echo Step (The requirement) ---
      - name: Echo Cache Result
        run: echo "Cache hit status for cache-c46fbd2: ${{ steps.cache-dependencies.outputs.cache-hit }}"

      # --- 4. Example: Run Tests (Placeholder) ---
      - name: Run Tests
        run: echo "Running tests after setup..."
