name: CI with Dependency Caching

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: prime-cache-c46fbd2
        uses: actions/checkout@v3

      - name: 24f2000662@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
        
